# Generated by Django 5.0.4 on 2024-05-25 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventtario', '0002_libro_remove_book_authors_remove_book_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='inventtario.category'),
        ),
    ]
