# Generated by Django 5.0.4 on 2024-05-27 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventtario', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
